### ISSUE TITLE
 five-limit just intonation

### ISSUE THREAD

**Issue by SamuelMiller** [billhails/MuseScore-plugins#8]
Hello is the just intonation of the plugin five-limit just intonation? Also, please consider adding the option of changing the root from C to another key?

**Comment by billhails** [comment]
I honestly hadn't heard of five-limit tuning until you asked, since I don't claim to be an expert. I looked it up on Wikipedia and I get the sense of it, and at a guess I'd say the just intonation is five-limit because it claims to be as described [here](http://leware.net/temper/temper.htm#_nr_308).

On the topic of changing the root key, yes it's a much-needed feature. I have some time off over Christmas, no promises but I'll see what I can do.

**Comment by billhails** [comment]
It was easier than I thought, the new version allows you to choose the root note. Enjoy!

**Comment by SamuelMiller** [comment]
Thanks! Have you updated the uploaded plugin on Musescore to this new version, yet?
https://musescore.org/en/project/tunings-and-temperaments

**Comment by billhails** [comment]
oops, good point, I'll do that now
